### PR TITLE
Update concatenation algorithm to prevent strings larger than the max length

### PR DESCRIPTION
**Pull request by ljharb**
Per https://github.com/ljharb/proposal-string-pad-left-right/issues/11#issuecomment-148591760.

### CODE REVIEW

**Comment by ljharb** [comment]
@michaelficarra, do you think these changes would handle the issue you pointed out?

**Comment by michaelficarra** [comment]
Instead of comparing `2 * fLen` to 2<sup>53</sup> - 1, you should compare `fLen` to `fillLen - fLen`. We're already guaranteed `fillLen` is within the 2<sup>53</sup> - 1 bound, and then we don't duplicate that magic number outside of `ToLength`.

**Comment by ljharb** [comment]
I'm all for avoiding the magic number - just like with this initial algorithm I suspect I'm a small epiphany away from understanding what you're suggesting.

Let's see: `fLen` is already less than `fillLen`, so `fillLen - fLen` will be the remaining number of characters it needs to add - so when `fLen` is larger than `fillLen - fLen`, we'll need to truncate `F` before concatenating, and then assuming we truncate, the "max length" scenario never occurs?

**Comment by michaelficarra** [comment]
Yep. Sounds like you understand to me.

**Comment by ljharb** [comment]
This change seems to obviate the need for `truncatedStringFiller` entirely, since the length of `F` is never larger than `fillLen`. Updating shortly!

**Comment by michaelficarra** [comment]
No, it is still needed for the case where `fillString` is longer than `fillLen`.

**Comment by ljharb** [comment]
ahh, you're right. k, updated

**Comment by michaelficarra** [comment]
I love it. :shipit:

**Pull request merged**
